### ISSUE TITLE
Usable with Subfolder and Port ?

### ISSUE THREAD

**Issue by tamaskan** [go-vikunja/desktop#1]
Hi,

i tried using it with a vikunja-url like this: https://vikunja.domain/vikunjaapi/:443 but it only gave me an error like "Could not find or use Vikunja installation at "vikunja.domain:3456""

**Comment by kolaente** [comment]
How are you hosting it? How is the `/api/v1/info` path reachable in your config?

**Comment by tamaskan** [comment]
It works now, i guess it was just some kind of caching-issue
