### ISSUE TITLE
Adding to AUR?

### ISSUE THREAD

**Issue by tio-trom** [go-vikunja/desktop#3]
Do you plan to add this to AUR or Fltapak? Thanks!

**Comment by kolaente** [comment]
I've never published a package to the AUR but shouldn't be too hard.

**Comment by igormp** [comment]
Someone did add it to AUR, maybe this could be closed and the link added to the README? (clearly stating that it's not an official package, ofc)

https://aur.archlinux.org/packages/vikunja-desktop-bin

**Comment by kolaente** [comment]
Do you want to send a PR for the readme?

**Comment by igormp** [comment]
Sure! Do you also accept PRs here, or only on your gitea instance?

**Comment by kolaente** [comment]
Only on the Gitea instance, this here is only a mirror.
