### ISSUE TITLE
When can I keep an eye on releases?

### ISSUE THREAD

**Issue by tio-trom** [go-vikunja/desktop#5]
I would like to know when you will release a new version but I do not see a Releases page...

**Comment by kolaente** [comment]
Releases happen [in the official repo](https://kolaente.dev/vikunja/desktop/releases) - you could either watch that repo or subscribe to our newsletter where we announce releases as well (on [the homepage](https://vikunja.io) on the bottom of the page).

**Comment by tio-trom** [comment]
Thanks. Following now.
