### ISSUE TITLE
Standalone Mode?

### ISSUE THREAD

**Issue by Iceman248** [go-vikunja/desktop#6]
I've tried 0.19, plus Unstable, can't see any way to use in standalone mode. I didn't find anything on it. How do I use like this?

**Comment by kolaente** [comment]
What do you mean with "standalone mode"?

**Comment by Iceman248** [comment]
> What do you mean with "standalone mode"?

Quote from website.

"Starting with version 0.15.0, Vikunja’s frontend is available as a standalone desktop app for linux and windows devices. This means you can run it on your desktop without the need to install the frontend."

**Comment by kolaente** [comment]
You'll still need to host an api somewhere. It's just not necessary to host a frontend as well. You can do that locally as well: https://vikunja.io/docs/install-backend/

**Comment by Iceman248** [comment]
Thanks, I get it now.. I think. I was able to get it going.
