### ISSUE TITLE
First draft for flatpak application 

### ISSUE THREAD

**Issue by lpyparmentier** [go-vikunja/desktop#7]
Hello,

I really like your app for my personal to-do that I self host btw. I also like to have my different GUI apps containerized. I will not debate between snap, appimage, or flatpak, but I have a preference for the latest (based on bubblewrap and user friendly).

In case you want to release your app on flathub.org in the future, this first draft might be useful: https://gitlab.parmentier.io/lparmentier/flatpak-vikunja 

e.g. I guess it might be improved by building it with yarn, by cloning this repo instead of downloading the binaries from dl.vikunja.io, such that it can be build on other platforms. But that's enough for me right now..

Cheers !

**Comment by kolaente** [comment]
Nice work! I think there's a backlog item somewhere to release the Desktop app in stores in the future. I'll add a link to your repo.
We're also considering moving to tauri but there's still a few things to iron out with that and we're not pressured.

Your gitlab has a self-signed certificate, is that intentional?

**Comment by lpyparmentier** [comment]
I'll check Tauri ! Never heard about it :) 

Yes it is [intentional](ca.parmentier.io) (a pinch of paranoia by no trusting free root CA xD, and I wanted to manage my own signatures). And since I'm almost the only user on my services, I did not care of using "preregistered" root CA (e.g. lets encrypt).

**Comment by RaptaG** [comment]
Hello @lpyparmentier! I'm trying to clone your repository (`git clone ssh://git@gitlab.parmentier.io:24/lparmentier/flatpak-vikunja.git`) but I get this:

```
Cloning into 'flatpak-vikunja'...
git@gitlab.parmentier.io: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

What should I do?

**Comment by RaptaG** [comment]
Nvm I downloaded it as a `.tar.gz`

**Comment by lpyparmentier** [comment]
Hey @RaptaG it certainly because ssh can't be use anonymously, so you can't clone it that way, I'm pretty sure you can use `https://...` instead

I've also quickly look your discussion on flathub, I'm truly sorry for the lack of respect from the guy, that's also why I do no contribute there. I like the concept (flatpak, bublewrap container), but flathub.org is a kind of nightmare to my point of view (the way it works concerning update/"security concern", and by those who managed it). I've tried to contribute in the past, and I gave up (in case you're curious [streamdeck PR](https://github.com/flathub/flathub/pull/2648) and https://github.com/flatpak/flatpak-builder-tools/issues/245 )

That's why I did Vikunja for my personal usage :)

**Comment by RaptaG** [comment]
> Hey @RaptaG it certainly because ssh can't be use anonymously, so you can't clone it that way, I'm pretty sure you can use `https://...` instead
> 
> I've also quickly look your discussion on flathub, I'm truly sorry for the lack of respect from the guy, that's also why I do no contribute there. I like the concept (flatpak, bublewrap container), but flathub.org is a kind of nightmare to my point of view (the way it works concerning update/"security concern", and by those who managed it). I've tried to contribute in the past, and I gave up (in case you're curious [streamdeck PR](https://github.com/flathub/flathub/pull/2648) and https://github.com/flatpak/flatpak-builder-tools/issues/245 )
> 
> That's why I did Vikunja for my personal usage :) 

Yes unfortunately it is hard to communicate with them.

Since you are here, I'd love some help!

I asked for some help there, but got no answer..

Could you give me some feedback on https://github.com/flathub/flathub/pull/4319#issuecomment-1630943194

Thanks in advance @lpyparmentier

**Comment by RaptaG** [comment]
> Depending on how that discussion continues, we might as well just publish [single-file-bundles](https://www.electron.build/configuration/flatpak) on our own and not publish on flathub…

I'm doing my best to get it working on Flathub, I know it is a pain but this way it will reach out to more people
